function datasets= data_download_info
datasets= {...    
	mkData1('vicon_room1','V1_01_easy'), ...
    mkData1('vicon_room1','V1_02_medium'), ...
    mkData1('vicon_room2','V2_01_easy'), ...
    mkData1('vicon_room1','V1_03_difficult'), ...
    mkData1('vicon_room2','V2_02_medium'), ...
    mkData1('vicon_room2','V2_03_difficult'), ...
   };
return


function ret= mkData1(path1, ds)
dataId= ds;
urlPath= strcat('http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/',path1,'/',ds,'/');
urlFilename= ds;
urlFileext= '.zip';
localPathPrefix= 'im_';
ret= mkDataInfo( dataId, urlPath, urlFilename, urlFileext, localPathPrefix );
return


function ret= mkDataInfo( dataId, urlPath, urlFilename, urlFileext, localPathPrefix )
dname=  [localPathPrefix urlFilename];
ofname= [dname urlFileext];
ret= struct('dataId',dataId, ...
    'url', [urlPath, urlFilename, urlFileext], ...
    'ofname', ofname, ...
    'mkfolder', dname );
